# Step 1: Build React App
FROM node:lts-alpine AS builder

WORKDIR /app-ui

COPY package.json package-lock.json* ./
RUN npm install --frozen-lockfile --legacy-peer-deps

COPY . .
RUN npm run build

# Step 2: Use Nginx with Cloud Logging Support
FROM nginx:alpine

# Install Google Cloud Logging agent
RUN apk add --no-cache bash curl \
    && curl -sSO https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh \
    && bash add-google-cloud-ops-agent-repo.sh --also-install

# Remove default index page
RUN rm -rf /usr/share/nginx/html/*

# Copy custom Nginx configuration
COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf

# Copy built React static files
COPY --from=builder /app-ui/build /usr/share/nginx/html

# Expose port
EXPOSE 80

# Start Nginx with logging
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
